name: kripto_takip_uygulamasi

description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0


environment:
  sdk: "^3.5.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
